declare module '@mui/icons-material' {
  import { SvgIconComponent } from '@mui/material';
  const icons: { [key: string]: SvgIconComponent };
  export default icons;
  export const ShieldOutlined: SvgIconComponent;
  export const DashboardOutlined: SvgIconComponent;
  export const AddCircleOutline: SvgIconComponent;
  export const HistoryOutlined: SvgIconComponent;
  export const AssessmentOutlined: SvgIconComponent;
  export const Inventory2Outlined: SvgIconComponent;
  export const ReportProblemOutlined: SvgIconComponent;
  export const BarChartOutlined: SvgIconComponent;
  export const SettingsOutlined: SvgIconComponent;
  export const ChevronLeft: SvgIconComponent;
  export const ChevronRight: SvgIconComponent;
  export const LogoutOutlined: SvgIconComponent;
  export const Menu: SvgIconComponent;
  export const Search: SvgIconComponent;
  export const Logout: SvgIconComponent;
  export const CloudUploadOutlined: SvgIconComponent;
  export const CheckCircleOutlined: SvgIconComponent;
  export const ErrorOutlineOutlined: SvgIconComponent;
  export const DescriptionOutlined: SvgIconComponent;
  export const DownloadOutlined: SvgIconComponent;
  export const ArrowForwardOutlined: SvgIconComponent;
  export const RefreshOutlined: SvgIconComponent;
  export const VisibilityOutlined: SvgIconComponent;
  export const PictureAsPdfOutlined: SvgIconComponent;
  export const FilterListOutlined: SvgIconComponent;
  export const SearchOutlined: SvgIconComponent;
  export const ClearOutlined: SvgIconComponent;
  export const AddOutlined: SvgIconComponent;
  export const QrCodeOutlined: SvgIconComponent;
  export const LockOutlined: SvgIconComponent;
  export const AccountCircleOutlined: SvgIconComponent;
  export const TrendingUpOutlined: SvgIconComponent;
  export const ArrowBackOutlined: SvgIconComponent;
  export const ScheduleOutlined: SvgIconComponent;
  export const SpeedOutlined: SvgIconComponent;
  export const DocumentScannerOutlined: SvgIconComponent;
  export const PersonOutlined: SvgIconComponent;
  export const SecurityOutlined: SvgIconComponent;
}
